name: README build

on:
  push:
    branches:
      - main
    schedule:
      - cron: '0 */6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Main branch
        uses: actions/checkout@v1
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: yarn install
      - name: Generate README file
        run: node index.js
      - name: Commit and Push new README.md
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.README_GITHUB_TOKEN }}
          target_branch: main
